M48
; DRILL file {KiCad 8.0.8} date 2025-02-02T15:52:30-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-02T15:52:30-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X1.3429Y-0.6734
X1.5705Y-0.6734
T2
X1.1811Y-2.5591
X2.3228Y-0.3543
X2.3228Y-2.5591
M30
